# Generated by Django 5.2.7 on 2025-10-23 13:46

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "username",
                    models.CharField(
                        help_text="Введите имя пользователя",
                        max_length=50,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите адрес электронной почты", max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="Введите страну", max_length=50, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Введите город", max_length=50, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Введите номер телефона",
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение аватара",
                        null=True,
                        upload_to="users/avatars",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jfif", "jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Аватар",
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=100, null=True, verbose_name="Токен")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Подтвержден")),
                (
                    "telegram_chat_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Уникальный идентификатор чата для Telegram уведомлений",
                        null=True,
                        unique=True,
                        verbose_name="ID чата в Telegram",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Username в Telegram"),
                ),
                (
                    "telegram_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Включены ли уведомления в Telegram",
                        verbose_name="Telegram уведомления",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("users", "Пользователь"), ("manager", "Менеджер")],
                        default="users",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False, verbose_name="Заблокирован")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "db_table": "users",
                "permissions": [
                    ("block_user", "Может блокировать пользователей"),
                    ("disable_mailing", "Может отключать рассылки"),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "chat_id",
                    models.BigIntegerField(
                        help_text="Уникальный идентификатор чата с пользователем",
                        unique=True,
                        verbose_name="ID чата в Telegram",
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Username в Telegram"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата подключения")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram пользователь",
                "verbose_name_plural": "Telegram пользователи",
            },
        ),
    ]
